"""empty message

Revision ID: 4c11950d4b29
Revises: None
Create Date: 2015-08-19 12:41:45.103729

"""

# revision identifiers, used by Alembic.
revision = '4c11950d4b29'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
